### ISSUE TITLE
New SMARTMI Silent Smart Air Humidifier 2

### ISSUE THREAD

**Issue by DJay-X** [hassbian-ABC/homebridge-MiHumidifier#14]
Any chance to support New SMARTMI Humidifier 2 with Display? Probably zhimi.humidifier.ca4 | miotspec
Thanks

![New-SMARTMI-Silent-Smart-Air-Humidifier-2-For-Home-Air-Damper-Aroma-Diffuser-Essential-Oil-Mist](https://user-images.githubusercontent.com/3874239/79044903-68ea7580-7c08-11ea-8332-dcfc8831b67d.jpg)

**Comment by netRunner0** [comment]
I think it will work similarly ... Write if it does not work

**Comment by DJay-X** [comment]
Thanks. But unfortunately this didn't work for me.

```
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] Initializing MiHumidifier accessory...
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]***********************************************************
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]          MiHumidifierPlatform v%s by hassbian-ABC 0.1.1
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]  GitHub: https://github.com/hassbian-ABC/homebridge-MiHumidifier
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]***********************************************************
Mai 17 11:29:50 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:29:50] [zhimi.humidifier.ca4] [MiHumidifier][INFO]start success...
Mai 17 11:30:51 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:30:51] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG] - get Error: Error
Mai 17 11:30:51 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:30:51] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG] - get Error: Error
Mai 17 11:30:52 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:30:52] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG] - get Error: Error
Mai 17 11:30:56 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:30:56] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG] - get Error: Error
Mai 17 11:31:02 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:31:02] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG]HumidifierDehumidifier - Active - setActive Error: Error
Mai 17 11:31:34 raspberrypi-3BPlus homebridge[18092]: [2020-5-17 11:31:34] [zhimi.humidifier.ca4] [MiHumidifier][DEBUG] - get Error: Error
```

```
{
            "accessory": "MiHumidifier",
            "name": "zhimi.humidifier.ca4",
            "ip": "192.xxx.xxx.xx",
            "token": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
            "model": "ca4",
            "showTemperatureDisable": false,
            "showTemperatureSensorName": "Temp Humidifier",
            "updateTimer": 60
        },
```

![Napkin 17 05 20, 11 36 10 AM](https://user-images.githubusercontent.com/3874239/82140925-9db6a180-9832-11ea-9b17-6d3f78acad51.png)

**Comment by netRunner0** [comment]
All config please

**Comment by DJay-X** [comment]
Thanks for trying to help. 
What do you mean bei "all config"? 
Thats all what is showing up in the journal regarding MiHumidifier

**Comment by Maxmudjon** [comment]
https://www.npmjs.com/package/homebridge-smartmi-humidifier2

**Comment by DJay-X** [comment]
> https://www.npmjs.com/package/homebridge-smartmi-humidifier2

Thanks a lot @Maxmudjon 
Unfortunately it's not on your Repo here on GitHub. Any reason?
Using config-ui-x installation its only in Russian language. Any chance for English in a next update?

Thanks again for your work and sharing with the community. 👍

**Comment by DJay-X** [comment]
@Maxmudjon homebridge-smartmi-humidifier2 unfortunately not working for me and crashing homebridge. :(


```
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]: Error: Call to device timed out
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:     at retry (/usr/local/lib/node_modules/homebridge-smartmi-humidifier2/node_modules/miio/lib/device.js:229:18)
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:     at /usr/local/lib/node_modules/homebridge-smartmi-humidifier2/node_modules/miio/lib/device.js:242:8
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:  {
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:   code: 'timeout'
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]: }
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]: Error: Call to device timed out
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:     at retry (/usr/local/lib/node_modules/homebridge-smartmi-humidifier2/node_modules/miio/lib/device.js:229:18)
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:     at /usr/local/lib/node_modules/homebridge-smartmi-humidifier2/node_modules/miio/lib/device.js:242:8
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:  {
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]:   code: 'timeout'
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]: }
Jul 19 16:29:02 raspberrypi-3BPlus homebridge[16672]: [2020-7-19 16:29:02] Got SIGTERM, shutting down Homebridge...
```
